# ASFINAG dataset exploration

**Source**: Autobahnen- und Schnellstraßen-Finanzierungs-Aktiengesellschaft, Österreich  
**Link**: https://www.asfinag.at/verkehr-sicherheit/verkehrszaehlung/

In [4]:
import pandas as pd

def print_metadata(current_df):
    print(f'Das Dataframe hat {len(current_df)} Einträge')

In [12]:
df = pd.read_excel("Jahr23_ASFINAG_Verkehrsstatistik.xls")
print_metadata(df)
df.head()

Das Dataframe hat 2612 Einträge

,Autobahn,Station,Zählstellenname,Zählstellen-,Abschnitt (von - bis),Richtung,Fahrzeugklasse,DTVMS,DTVMF,DTVMO,DTVDD,DTVFR,DTVSA,DTVSF,Gezählte Tage,Geschätzte Tage,Legende
0,NaN,NaN,NaN,nummer,NaN,NaN,NaN,Mo-So,Mo-Fr,Mo,Di-Do,Fr,Sa,Sonn- und Feiertage,NaN,NaN,NaN
1,NaN,[km],NaN,NaN,NaN,NaN,NaN,Kfz/24h,Kfz/24h,Kfz/24h,Kfz/24h,Kfz/24h,Kfz/24h,Kfz/24h,NaN,NaN,NaN
2,A01,15.891,Pressbaum,955,Wien Auhof - Preßbaum,Staatsgrenze Walserberg,Kfz,-1,-1,-1,-1,-1,-1,-1,0.0,0.0,NaN
3,A01,15.891,Pressbaum,955,Wien Auhof - Preßbaum,Staatsgrenze Walserberg,"Kfz > 3,5t hzG",199.99726,259.616935,262.458333,268.413333,230.5,75.942308,71.769231,365.0,0.0,NaN
4,A01,15.891,Pressbaum,955,Wien Auhof - Preßbaum,Staatsgrenze Walserberg,"Kfz <= 3,5t hzG",-1,-1,-1,-1,-1,-1,-1,0.0,0.0,NaN

In [13]:
df = df[df["Autobahn"].notna() & df["Autobahn"].str.startswith("A")]
print_metadata(df)

Das Dataframe hat 2052 Einträge

In [14]:
df = df[df["Fahrzeugklasse"] == "Kfz <= 3,5t hzG"]
print_metadata(df)

Das Dataframe hat 684 Einträge

In [15]:
df = df[df["DTVMS"] != -1]
print_metadata(df)
df.head()

Das Dataframe hat 598 Einträge

,Autobahn,Station,Zählstellenname,Zählstellen-,Abschnitt (von - bis),Richtung,Fahrzeugklasse,DTVMS,DTVMF,DTVMO,DTVDD,DTVFR,DTVSA,DTVSF,Gezählte Tage,Geschätzte Tage,Legende
13,A01,26.833,Kn. Steinhäusl,751,Preßbaum - Kn. Steinhäusl,Staatsgrenze Walserberg,"Kfz <= 3,5t hzG",10676,10849,9760,10666,12446,10528,10133,358.0,7.0,NaN
16,A01,26.833,Kn. Steinhäusl,751,Kn. Steinhäusl - Preßbaum,Wien/Auhof,"Kfz <= 3,5t hzG",12111,12092,11693,11994,12766,11471,12694,301.0,64.0,NaN
19,A01,26.833,Kn. Steinhäusl,751,gesamt,gesamt,"Kfz <= 3,5t hzG",22787,22941,21453,22660,25212,21999,22827,299.0,66.0,NaN
31,A01,37.81,HASt St. Christophen,754,Altlengbach - St. Christophen,Staatsgrenze Walserberg,"Kfz <= 3,5t hzG",30994,29749,30373,28880,31813,30243,36402,182.0,122.0,NaN
34,A01,37.81,HASt St. Christophen,754,St. Christophen - Altlengbach,Wien/Auhof,"Kfz <= 3,5t hzG",31692,31459,26971,30355,38879,34409,30398,174.0,130.0,NaN

In [16]:
df = df.drop_duplicates(subset=["Station"], keep="last")
print_metadata(df)
df.head()

Das Dataframe hat 202 Einträge

,Autobahn,Station,Zählstellenname,Zählstellen-,Abschnitt (von - bis),Richtung,Fahrzeugklasse,DTVMS,DTVMF,DTVMO,DTVDD,DTVFR,DTVSA,DTVSF,Gezählte Tage,Geschätzte Tage,Legende
19,A01,26.833,Kn. Steinhäusl,751,gesamt,gesamt,"Kfz <= 3,5t hzG",22787,22941,21453,22660,25212,21999,22827,299.0,66.0,NaN
37,A01,37.81,HASt St. Christophen,754,gesamt,gesamt,"Kfz <= 3,5t hzG",62686,61208,57344,59235,70692,64652,66800,174.0,130.0,NaN
55,A01,50.285,St. Pölten/A1,409,gesamt,gesamt,"Kfz <= 3,5t hzG",62465,61254,57565,59449,70211,63858,65964,241.0,124.0,NaN
64,A01,56.5,St. Pölten Süd/A1,415,gesamt,gesamt,"Kfz <= 3,5t hzG",71038,69789,65967,67519,80272,72590,74556,233.0,132.0,NaN
73,A01,67.35,Poppendorf,423,gesamt,gesamt,"Kfz <= 3,5t hzG",56520,54139,50591,51937,64147,59589,63148,292.0,73.0,NaN

In [17]:
df = df[df["Geschätzte Tage"] <= 36]
print_metadata(df)
df.head()

Das Dataframe hat 107 Einträge

,Autobahn,Station,Zählstellenname,Zählstellen-,Abschnitt (von - bis),Richtung,Fahrzeugklasse,DTVMS,DTVMF,DTVMO,DTVDD,DTVFR,DTVSA,DTVSF,Gezählte Tage,Geschätzte Tage,Legende
91,A01,95.345,Ybbs,431,gesamt,gesamt,"Kfz <= 3,5t hzG",54496,51772,47926,49514,62238,58046,62053,342.0,23.0,NaN
100,A01,104.546,Neumarkt An Der Ybbs,977,gesamt,gesamt,"Kfz <= 3,5t hzG",54799,52008,48272,49674,62599,58476,62506,363.0,2.0,NaN
109,A01,115.536,Seisenegg,983,gesamt,gesamt,"Kfz <= 3,5t hzG",52020,48855,45296,46481,59394,56206,60741,334.0,31.0,NaN
118,A01,127.559,Ludwigsdorf,439,gesamt,gesamt,"Kfz <= 3,5t hzG",49465,46617,42930,44467,56603,53462,57136,361.0,4.0,NaN
145,A01,153.39,Kötting,450,gesamt,gesamt,"Kfz <= 3,5t hzG",53490,51538,48007,49425,61269,56568,58481,329.0,36.0,NaN

In [18]:
value_counts = df['Autobahn'].value_counts(dropna=False)
sorted_value_counts = value_counts.sort_index()
print(sorted_value_counts)

Autobahn
A01     14
A02     18
A04      6
A05      4
A07      3
A08      3
A09     14
A10     10
A11      1
A12     15
A13      1
A131     1
A14      7
A141     1
A21      1
A22      3
A23      2
A25      3
Name: count, dtype: int64

In [19]:
pd.to_pickle(df, "auswahl-zaehlstellen_36.pickle")

---
### (Optional:) Convert to .xlsx for manual inspection

In [ ]:
import pandas as pd

df = pd.read_pickle("auswahl-zaehlstellen_36.pickle")
df.to_excel("auswahl-zaehlstellen_36.xlsx")